name: Upload


on:
  workflow_dispatch: 
  
  
  
permissions:
  contents: write


jobs:


  upload:


    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v5
    
    - name: upload
      shell: bash
      env:
        ACCESS: ${{ secrets.ACCESS }}
        SECRET: ${{ secrets.SECRET }}
      run: |
        curl -C - -L -o "Microsoft Windows 95C (4.03.1216) (OSR2.5) (1997-11-26) English.7z" "https://winworldpc.com/download/c3b7c3bb-07c3-b3cb-8657-11c3a6e28094/from/c3ae6ee2-8099-713d-3411-c3a6e280947e"
        sha256sum "Microsoft Windows 95C (4.03.1216) (OSR2.5) (1997-11-26) English.7z"
        sha512sum "Microsoft Windows 95C (4.03.1216) (OSR2.5) (1997-11-26) English.7z"
        curl -X PUT \
               --upload-file "Microsoft Windows 95C (4.03.1216) (OSR2.5) (1997-11-26) English.7z" \
               -H "x-amz-auto-make-bucket:1" \
               -H "x-archive-meta-mediatype:software" \
               -H "x-archive-meta01-collection:operatingsystemcds" \
               -H "x-archive-meta02-collection:operatingsystemsoftware" \
               -H "x-archive-meta-title: Windows 95 OSR 2.5 (winworldpc.com reupload)" \
               -H "x-archive-meta-description: Windows 95 OSR 2.5 From WinWorld" \
               -H "User-Agent: curl" \
               -H "authorization: LOW $ACCESS:$SECRET" \
               "https://s3.us.archive.org/win95osr2.5-e0p96/Microsoft%20Windows%2095C%20%284.03.1216%29%20%28OSR2.5%29%20%281997-11-26%29%20English.7z"
env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
